### PR TITLE
Add 429 Retry for all Requests

### PR DESCRIPTION
**Pull request by tausifmuzaffar**

### CODE REVIEW

**Review by iamigo — CHANGES_REQUESTED** [review]
i see the backoff, but is there a max number of retries for any given request, or can it potentially just keep retrying indefinitely? imagine a scenario where the token belongs to a user who is also engaged in other api activity and using up rate limit at the same time... what happens when the user is continually over limit?

**Review by iamigo — CHANGES_REQUESTED** [review]
where are tests?

**Review by iamigo — APPROVED** [review]

**Review by kriscfoster — APPROVED** [review]

**Comment by kriscfoster** [comment]
Some weird conflict with a PR that went in yesterday, tests failing

**Comment by tausifmuzaffar** [comment]
@kriscfoster fixed

**Pull request merged**
