### PR TITLE
Configurable RT Socket Connection URL

### PR DESCRIPTION
**Pull request by kriscfoster**
- Extracted rtEventNames to a separate config file as refocusConnectSocket function reached it's max amount of statements (20)
- If bot config file contains refocusRealtimeUrl then use the new refocusRealtimeUrl to connect
- **TODO** when this goes through: add `refocusRealtimeUrl: process.env.REFOCUS_REALTIME_URL` to config file of bots with a backend

### CODE REVIEW

**Comment by BrandonMurnane** [comment]
were u able to get this working to receive updates ?

**Comment by kriscfoster** [comment]
@BrandonMurnane nope, meeting with Ian to talk about this.. We think it could be something on Refocus side because even the room isn't receiving the RT updates. If you join a room and then do some stuff, another browser with the same room open doesn't get the updates.

**Review by BrandonMurnane — APPROVED** [review]
code looks good would like to wait before we have working before merge though

**Review by cassiodias — APPROVED** [review]

**Comment by kriscfoster** [comment]
@BrandonMurnane is it okay to merge this now? It won't have any effect right now as the env var won't be set.

Should I create a PR on all appropriate bots to add the refocusRealtimeUrl attribute to the config file?

**Review by ConalCosgrove — APPROVED** [review]

**Pull request closed without merging**
